### ISSUE TITLE
TO = CEMAL Step by step how to use git for this project

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/agile-development-group2-all-about-trees#1]
## NO PROJECT WITHOUT GIT
This project won't work without you knowing how to use git. Follow this step to start practicing git. 
How to clone a repo, use VSCode, and push. 
I'm addressing this issue as a bug cause it's blocking the entire project and need to be solve ASAP. Please make it **PRIORITY!**

**DO NOT COPY PASTE THE CODE!** Type it on your terminal

Thanks in advance!

## Step 1

- [x] - Open the repo you want to clone
- [x] - Click `code`
- [x] - Copy the HTTPS link
- [x] - Open the terminal on your computer
- [x] - `pwd` -> to know on which path are you working now
- [x] - `cd desktop` -> to work on desktop
- [x] - `mkdir agile-group2`-> to create a new directory/folder called _**agile-group2**_
- [x] - `cd agile-group2`-> to work in folder _**agile-group2**_
- [x] - `git clone <tpaste the link you copied from github repo>` 
</br> in our case the command gonna be `git clone https://github.com/HYF-Class20/agile-development-group2-all-about-trees`

## Step 2

- [x] - Go to VSCode
- [x] - Open your repo
- [x] - `git pull` to get the newest version of master repo
- [x] - `git checkout -b <branch name>` to work out of master repo and creating a new branch. </br>
- [x]   Example `git checkout -b add-home-page` with this command you're out of master repo, creating a branch called **add-home-page** and work inside that branch.
_**!!NEVER WORK INSIDE MASTER REPO!! NEVER CHANGE ANYTHING IN THE MASTER!! ALWAYS WORK IN BRANCH!!**_
_**DO NOT USE CAPITAL LETTER TO NAME A BRANCH, FOLDER OR FILE. IT WILL CAUSE ERROR!**_
- [x] - `npm i` -> to install npm. You need this for linting!
- [x] - Work inside folder `planning`
- [x] - Do your task
- [x] - Once your task is done, you run `git status` -> to see what changes you've made
- [x] - `git add <name of the files you've changes>` this command is to add your spesific changes.
 </br> **IT'S NOT RECOMMENDED TO USE  `git add .`**
- [x] - `git status` to see the changes you've made
- [x] - No red message on git status, all green.
- [x] - `git commit -m "<meaningful message>"`

## Step 3
Linting! This step is to check your code quality. Your code MUST passed the check. 
Except the result for command `npm run spell-check`you can ignore.

Linting command :

- [x] `npm run format`
- [x] `npm run format:check`
- [x] `npm run spell-check`
- [x] `npm run lint:ls`
- [x] `npm run lint:md`
- [x]  If all of them passed then you can push the code
- [x] `git push origin <your branch name>`
- [x] **Don't push anything yet to our repo.**

**Comment by Gopiben** [comment]
i finish step 1 thankyu so much

*Vriendelijke groeten*
*Gopien SAVANI | +32 484 75 01 38*

**Comment by GabriellaLohy** [comment]
@Gopiben Hi Gopi. I created an issue for you. Please use that one. Click on the link. 
[GOPI Step to use git]( https://github.com/HYF-Class20/agile-development-group2-all-about-trees/issues/2)

Ps : Please be active on slack so we have a progress

**Comment by Gopiben** [comment]
thankyu so much i follow this step
*Vriendelijke groeten*
*Gopien SAVANI | +32 484 75 01 38*
